disabled_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - collection_alignment
  - conditional_returns_on_newline
  - convenience_type
  - cyclomatic_complexity
  - direct_return
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_length
  - file_name
  - file_types_order
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - inclusive_language
  - implicit_return
  - indentation_width
  - large_tuple
  - literal_expression_end_indentation
  - local_doc_comment
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - non_optional_string_data_conversion
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - period_spacing
  - prefer_nimble
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_string_enum_value
  - redundant_type_annotation
  - required_deinit
  - self_binding
  - sorted_enum_cases
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_alignment
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - let_var_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_between_cases
  - xct_specific_matcher
  
opt_in_rules:
  - blanket_disable_command
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - force_cast
  - force_try
  - identical_operands
  - ns_number_init_as_function_reference
  - return_value_from_void_function
  - superfluous_else
  - unhandled_throwing_task
  - unowned_variable_capture
  - weak_delegate
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma_inheritance
  - comma
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - custom_rules
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_none_name
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_unwrapping
  - ibinspectable_in_extension
  - implicit_getter
  - implicitly_unwrapped_optional
  - invalid_swiftlint_command
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
  - lower_acl_than_parent
  - mark
  - sorted_first_last
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - nsobject_prefer_isequal
  - opening_brace
  - operator_whitespace
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_subject
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_objc_attribute
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_self_in_closure
  - redundant_set_access_control
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - self_in_property_initialization
  - shorthand_operator
  - shorthand_optional_binding
  - single_test_class
  - sorted_imports
  - superfluous_disable_command
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unavailable_condition
  - unneeded_break_in_switch
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_function_in_ternary
  - void_return
  - xctfail_message
  - yoda_condition
  - line_length
  - implicit_return

line_length:
  warning: 160
  error: 200
  ignores_comments: true
  ignores_urls: true

analyzer_rules:
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import
  
excluded:
  - Carthage
  - Pods

unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder # we can't detect uses of string interpolation of swift syntax nodes
    - SwiftLintFramework # now that this is a wrapper around other modules, don't treat as unused
